DROP TABLE IF EXISTS Yllapitaja CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS RaakaAine CASCADE;
DROP TABLE IF EXISTS Lasityyppi CASCADE;
DROP TABLE IF EXISTS Juomatyyppi CASCADE;
DROP TABLE IF EXISTS Drinkkiohje CASCADE;



